In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray',arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')
arr2 = arr

In [9]:
np.savez('ziparray.npz',x= arr1, y = arr2)

In [10]:
archive_arr = np.load('ziparray.npz')

In [12]:
archive_arr

In [13]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [14]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [17]:
arr = np.loadtxt('mytextarray.txt', delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])