In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index = ['T','U','V'])
ser2 = Series([3,4],index = ['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2= DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [17]:
dframe1

X         Y         Z
0 -0.090293 -0.927221  0.553083
1 -0.230623 -0.567052  0.072870
2 -0.752632  0.430627  0.486351
3 -0.748778  0.769490 -1.584287

In [18]:
dframe2

Y         Q         X
0  0.417629 -0.384895  2.256609
1  0.632549 -1.183110  2.051801
2  0.737505 -0.299145 -1.585725

In [19]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.090293 -0.927221  0.553083       NaN
1 -0.230623 -0.567052  0.072870       NaN
2 -0.752632  0.430627  0.486351       NaN
3 -0.748778  0.769490 -1.584287       NaN
0  2.256609  0.417629       NaN -0.384895
1  2.051801  0.632549       NaN -1.183110
2 -1.585725  0.737505       NaN -0.299145

In [20]:
pd.concat([dframe1,dframe2],ignore_index = True)

X         Y         Z         Q
0 -0.090293 -0.927221  0.553083       NaN
1 -0.230623 -0.567052  0.072870       NaN
2 -0.752632  0.430627  0.486351       NaN
3 -0.748778  0.769490 -1.584287       NaN
4  2.256609  0.417629       NaN -0.384895
5  2.051801  0.632549       NaN -1.183110
6 -1.585725  0.737505       NaN -0.299145