In [1]:
import numpy as np


In [2]:
my_list1 = [1,2,3,4]

In [3]:
array1 = np.array(my_list1)

In [4]:
array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [66,33,99,55]

In [6]:
my_lists = [array1, my_list2]

In [7]:
my_array = np.array(my_lists)

In [8]:
my_array

array([[ 1,  2,  3,  4],
       [66, 33, 99, 55]])

In [10]:
my_array.shape

(2, 4)

In [11]:
my_array.dtype

dtype('int32')

Special case arrays

In [13]:
new_array = np.zeros(5)

In [14]:
new_array.dtype

dtype('float64')

In [15]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.arange creates arrays of the desired choice. It can take arguments ('start of the array', 'end point of the array', 'interval'

In [17]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

Using arrays and scalars

In [21]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [22]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [23]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [25]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

Indexing Arrays

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[1:5] 

array([1, 2, 3, 4])

In [30]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
 arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
slice_off_arr = arr[0:6]

In [36]:
slice_off_arr

array([0, 1, 2, 3, 4, 5])

In [37]:
slice_off_arr[:]= 99
slice_off_arr

array([99, 99, 99, 99, 99, 99])

In [38]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_copy = arr.copy()

In [40]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
arr_2d = np.array(([5,10,10], [20,25,30],[35,30,45]))
arr_2d

array([[ 5, 10, 10],
       [20, 25, 30],
       [35, 30, 45]])

In [43]:
arr_2d[1]

array([20, 25, 30])

In [44]:
arr_2d[1,2]

30

In [45]:
arr_2d

array([[ 5, 10, 10],
       [20, 25, 30],
       [35, 30, 45]])

In [46]:
arr_2d[:2,1:]

array([[10, 10],
       [25, 30]])

In [47]:
arr_2d[2]

array([35, 30, 45])

In [50]:
arr_2d[1:,1:]

array([[25, 30],
       [30, 45]])

In [51]:
arr2d = np.zeros((10,10))

In [52]:
arr2d


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
arr2d_length = arr2d.shape[1]
arr2d_length

10

In [63]:
for i in range(arr2d_length):
    arr2d[i]= i

In [64]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [66]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [67]:
arr2d[[1,5,6,7]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

Array Transposition

In [68]:
arr = np.arange(50).reshape((10,5))

In [69]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

Array transposition .T function

In [71]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [73]:
np.dot(arr.T , arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [74]:
arr3d = np.arange(50).reshape((5,5,2))

In [76]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [77]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [78]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [80]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

Universal Array Functions

In [81]:
arr = np.arange(0,11)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [84]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [85]:
A = np.random.randn(10)

In [86]:
A

array([ 0.70281938,  0.9105741 , -1.55366596,  0.59400969,  0.35051766,
        0.1649912 , -0.81714893,  0.28138491, -0.55888074, -0.10084483])

In [87]:
B = np.random.randn(10)

In [88]:
B

array([ 0.82955718, -0.1443509 , -0.06945209,  0.5134236 ,  1.11695949,
       -0.54304214,  0.05414656, -0.29038717, -0.227093  ,  2.88981134])

In [89]:
# Binary functions
np.add(A,B)

array([ 1.53237657,  0.7662232 , -1.62311805,  1.10743329,  1.46747715,
       -0.37805094, -0.76300237, -0.00900226, -0.78597374,  2.7889665 ])

In [91]:
np.maximum(A,B)

array([ 0.82955718,  0.9105741 , -0.06945209,  0.59400969,  1.11695949,
        0.1649912 ,  0.05414656,  0.28138491, -0.227093  ,  2.88981134])

In [92]:
np.minimum(A,B)

array([ 0.70281938, -0.1443509 , -1.55366596,  0.5134236 ,  0.35051766,
       -0.54304214, -0.81714893, -0.29038717, -0.55888074, -0.10084483])